# Generated by Django 5.1.3 on 2024-11-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_avatar', models.FileField(upload_to='')),
                ('user_data_register', models.DateTimeField(auto_now_add=True)),
                ('user_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Requestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.CharField(max_length=255)),
                ('request_date_created', models.DateTimeField(auto_now_add=True)),
                ('request_correct', models.CharField(choices=[('T', 'Correct'), ('N', 'NotCorrect')], max_length=10)),
                ('request_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_title', models.CharField(max_length=255)),
                ('quest_text', models.CharField(max_length=255)),
                ('quest_date_created', models.DateTimeField(auto_now_add=True)),
                ('quest_rating', models.IntegerField()),
                ('quest_request', models.ManyToManyField(to='app.requestions')),
                ('quest_tag', models.ManyToManyField(to='app.tag')),
                ('quest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
