# Generated by Django 5.1.3 on 2024-11-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_alter_questions_quest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quest_request',
            field=models.ManyToManyField(blank=True, null=True, to='app.requestions'),
        ),
    ]
