# Generated by Django 5.1.3 on 2024-11-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_user_alter_profile_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_password',
        ),
    ]
