# Generated by Django 5.1.3 on 2024-11-07 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_question_answer_remove_question_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestions',
            name='request_user_id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_avatar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_data_register',
            new_name='data_register',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name_tag',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('correct', models.CharField(choices=[('T', 'Correct'), ('N', 'NotCorrect')], max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('answer', models.ManyToManyField(to='app.answer')),
                ('tag', models.ManyToManyField(to='app.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Requestions',
        ),
    ]
