# Generated by Django 5.1.3 on 2024-11-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_requestions_request_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(null=True, to='app.answer'),
        ),
    ]
