# Generated by Django 5.1.3 on 2024-11-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(blank=True, null=True, to='app.answer'),
        ),
    ]
