# Generated by Django 5.1.3 on 2024-11-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_answerlike_questionlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
    ]
